acme_inventory:
    resource: "@AcmeInventoryBundle/Controller/"
    type:     annotation
    prefix:   /

inventory:
 resource:	Acme\InventoryBundle\Controller\InventoryController
 type:	rest
 prefix: /api